package verify

import (
	"archive/zip"
	"bytes"
	"fmt"
)

// buildMinimalNupkg builds a minimal but valid .nupkg in memory: a bare zip
// containing {id}.nuspec at the root plus one content file. This is
// deliberately not full OPC-compliant (no _rels, [Content_Types].xml, or
// core-properties psmdcp) — that's what self-hosted v3 servers like
// BaGetter and Barn actually parse. nuget.org's stricter reader would need
// more; that's out of scope for this conformance tool.
func buildMinimalNupkg(id, version string) ([]byte, error) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	nuspec := fmt.Sprintf(`<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>%s</id>
    <version>%s</version>
    <authors>nugctl</authors>
    <description>Transient package generated by nugctl feed verify --push.</description>
    <files>
      <file src="readme.txt" target="readme.txt" />
    </files>
  </metadata>
</package>`, id, version)

	nuspecW, err := zw.Create(id + ".nuspec")
	if err != nil {
		return nil, err
	}
	if _, err := nuspecW.Write([]byte(nuspec)); err != nil {
		return nil, err
	}

	readmeW, err := zw.Create("readme.txt")
	if err != nil {
		return nil, err
	}
	if _, err := readmeW.Write([]byte("generated by nugctl feed verify --push\n")); err != nil {
		return nil, err
	}

	if err := zw.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
